version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword
      MYSQL_DATABASE: library_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  librarymanagement:
    build:
      context: ../LibraryManagement
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/library_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysqlpassword
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - app-network

  libraryhub:
    build:
      context: ../LibraryHub
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hub_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysqlpassword
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - app-network

  libraryadvisor:
    build:
      context: ../LibraryAdvisor
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/libraryadvisor_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysqlpassword
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
