apiVersion: v1
kind: Service
metadata:
  name: librarymanagement-service
spec:
  selector:
    app: librarymanagement
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: NodePort
